export const IMPLEMENTATION_STORES_PATH_SOURCE = "globalThis";
export const IMPLEMENTATION_STORES_PATH_VAR_NAME = "implementationStores";
export const IMPLEMENTATION_STORES_PATH_REQ = IMPLEMENTATION_STORES_PATH_VAR_NAME + "_require";
